json = {
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyMjZlOTY4OC01ZTgwLTRmMjEtYjY1NS02YWNhYTMxZjE4ZjEiLCJjbGllbnRJZCI6ImFpaWFwb2MtOTJjZDdjMjYtM2NhNi00MDRkLTliMWMtM2RlZTExYTE1YzgxIiwicm9sZSI6IkNsaWVudFVzZXIiLCJzZXNzaW9uSWQiOiIzZThhYzhiZS1mNzQzLTQ4Y2UtYjEyNi1jNzk3MTcwOGNmZjMiLCJzY29wZXMiOiJhY2NvdW50cyBvZmZsaW5lX2FjY2VzcyIsIm5iZiI6MTY5MTU4MTAxNCwiZXhwIjoxNjkxNTg0NjE0LCJpYXQiOjE2OTE1ODEwMTR9.bnfaB0nNqQhXO6fHeVmnuZUk2jKRRwIeszd8FNrTq7U",
    "expires_in": 3600,
    "redirect_uri": None,
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyMjZlOTY4OC01ZTgwLTRmMjEtYjY1NS02YWNhYTMxZjE4ZjEiLCJjbGllbnRJZCI6ImFpaWFwb2MtOTJjZDdjMjYtM2NhNi00MDRkLTliMWMtM2RlZTExYTE1YzgxIiwiY29uc2VudElkcyI6IjQyMGMwZGI2LWYxYWItNGFmNi04MGMyLTdlZmUzZTU0Njc0NiIsInJvbGUiOiJSZWZyZXNoVG9rZW4iLCJzZXNzaW9uSWQiOiIzZThhYzhiZS1mNzQzLTQ4Y2UtYjEyNi1jNzk3MTcwOGNmZjMiLCJzY29wZXMiOiJhY2NvdW50cyBvZmZsaW5lX2FjY2VzcyIsIm5iZiI6MTY5MTU4MTAxNCwiZXhwIjoxNjkyNzkwNjE0LCJpYXQiOjE2OTE1ODEwMTR9.0ZbSzjnfC1LEE4-1O38JUGroErnnQcm_NOCBueZ2APs",
    "token_type": "bearer"
}

print(json.get('access_token'))

https://app-aiia-test.azurewebsites.net/api/AiiaRefreshToken?code=0MuiXXJ1VF5MYPdKaQNSFcUAF8Oyj7Vaka3U0wP352RSAzFuLvecDw==
https://app-aiia-test.azurewebsites.net/api/AiiaRefreshToken?code=0MuiXXJ1VF5MYPdKaQNSFcUAF8Oyj7Vaka3U0wP352RSAzFuLvecDw==